### ISSUE TITLE
Cannot place blocks.

### ISSUE THREAD

**Issue by henry242** [Goodlyay/Nas#1]
I made a new server with 1.9.3.2, following all the steps, etc.
Unfortunately, I can break blocks, but not place them. 
I have made myself Nobody, Guest, etc. Nothing works.

I know you probably aren't working on this, but it would be nice to get it working.

Edit: So right clicking works with deletable off, but it just acts like a normal right click like on normal servers, and it doesn't use up the NAS blocks.

**Comment by Goodlyay** [comment]
Thanks for the bug report. I tested it, and it turns out this is a bug in the latest release of MCGalaxy, but it works if you use the latest dev build. You can get the latest dev build here: https://123dmwm.com/MCGalaxy/
Let me know if that works.

**Comment by henry242** [comment]
So:
I got the latest dev build, redownloaded the assets.zip just to be sure, but... now the console fills up with errors:
Method NotAwesomeSurvival.Nas.OnPlayerMove errored when calling OnPlayerMove event
!!!Error (Object reference not set to an instance of an object.) - See Logs tab for more details

The plugin also doesn't generate a world, like it should.

I have attached a video (sorry about the bad quality) to show you what's happening.

[2021-06-08 15-08-10.zip](https://github.com/Goodlyay/Nas/files/6619341/2021-06-08.15-08-10.zip)

**Comment by UnknownShadow200** [comment]
Can you please upload error log file from logs/errors folder

**Comment by Goodlyay** [comment]
If it doesn't generate a map, it means it doesn't understand that this is the "first time" the plugin loaded. Are you sure you deleted absolutely everything? As in, every single folder that MCGalaxy makes. Try doing that, then following the install instructions again.

**Comment by henry242** [comment]
Yes, I made sure to delete everything, even the entire folder. I may need to get the release and then replace the exe and dll from latest.zip.

**Comment by henry242** [comment]
Accidentally pressed the close button, sorry.
I made sure to delete the entire folder then put latest.zip in the folder.

**Comment by Goodlyay** [comment]
So I'm pretty sure I see the problem now.
Originally, MCGalaxy loaded plugins, then loaded the main level, in that order. I needed the main level to be loaded in order to setup NAS correctly. But NAS already loads before main is done loading. So I added an event when main is loaded that allows NAS to finish setting itself up.

However... UnknownShadow recently fixed it so that plugins always load after the main level has been completely loaded. This means that now NAS never actually receives the event where main finished loading, because main was loaded before the plugin started at all. Unfortunately the build I was testing with was one commit earlier than Unk's fix so I didn't catch the issue.

**Comment by Goodlyay** [comment]
Try now. I've made a commit that should address the issue. As usual, make sure you start with a fresh copy of MCGalaxy just to be safe.

**Comment by henry242** [comment]
It works. Thank you so much, Goodly (and Unk)!

**Comment by Goodlyay** [comment]
Closed via 35d4fc62d46aa7d67a11d352508ee79d7139a3d5
